#
# Copyright (c) 2016-2022 AG (ag@localhost.lan)
# This is free software, licensed under the GNU General Public License v3.
#


include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for icc
LUCI_DEPENDS:=+icc
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-3.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
