#!/bin/sh /etc/rc.common
. /lib/functions/network.sh

USE_PROCD=1
START=97
STOP=01

PROG="icc"
CONF="/etc/config/$PROG"
PIDFILE="/var/run/$PROG.pid"
SCRIPT="/usr/bin/$PROG.sh"
ICC_STATE="/var/run/icc.state"
interface=


get_var() {
	config_get interface "$1" interface
}

start_service() {
	procd_open_instance
	procd_set_param command $SCRIPT $interface $device
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-3} ${respawn_retry:-3}
#	procd_set_param env INTERFACE="$interface" DEVICE=""
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_set_param pidfile $PIDFILE
	procd_close_instance
}

service_triggers() {
	config_load $PROG
	config_foreach get_var $PROG

	for i in $interface; do
		procd_add_reload_interface_trigger $i
	done
	
	procd_add_reload_trigger $PROG
}

reload_service() {
	stop
	start
}

service_stopped() {
	rm -f  $ICC_STATE
}

