#!/bin/sh
if [ ! -f /etc/config/icc ];then
	uci import icc < /dev/null
	uci -q batch <<-EOF >/dev/null
	delete icc.@icc[-1]
	add icc icc
	set icc.@icc[-1].debug=0
	set icc.@icc[-1].timeout=5
	set icc.@icc[-1].interval=300
	add_list icc.@icc[-1].interface=wan
	add_list icc.@icc[-1].interface=wwan
	add_list icc.@icc[-1].host=openwrt.org
	add_list icc.@icc[-1].host=8.8.8.8
	add_list icc.@icc[-1].host=8.8.4.4
	commit icc
	EOF
fi
exit 0

