#!/bin/sh /etc/rc.common
### internet connection checker

USE_PROCD=1
START=99
STOP=01

prog=icc
conf="/etc/config/$prog"
pidfile="/var/run/$prog.pid"
script="/usr/bin/$prog.script"

do_log(){
	logger -s -p notice -t "$prog" "$@"
}

start_service() {
	do_log "start $prog service"
	# Reading config
	
	procd_open_instance "$prog"
	procd_set_param command $script
	procd_set_param file $conf
	procd_set_param pidfile $pidfile
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-3} ${respawn_retry:-3}
	procd_close_instance
	procd_add_reload_trigger "$conf"
	procd_add_restart_trigger "$conf"
}

service_triggers()
{
	procd_add_reload_trigger "$conf"
}

service_stopped() {
	do_log "stopped $prog service"
}

restart_service() {
	do_log "restart $prog service"
}






