#!/bin/sh /etc/rc.common
. /lib/functions/network.sh

USE_PROCD=1
START=97
STOP=01

prog="icc"
conf="/etc/config/$prog"
pidfile="/var/run/$prog.pid"
script="/usr/bin/$prog.sh"
logtag="$prog"
service_action='start'

start_service() {
	config_load "$prog"
	config_get interface $prog interface
	
	network_flush_cache
	network_get_device device $interface

	procd_open_instance "${prog}"
	procd_set_param command $script $interface $device
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-3} ${respawn_retry:-3}
	procd_set_param env LOGTAG="$logtag" SERVICE_ACTION="$action" INTERFACE="$interface" DEVICE="$device"
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_set_param pidfile $pidfile
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "${prog}"
	procd_add_reload_interface_trigger $interface
}

reload_service() {
	stop
	start
}

service_stopped() {
	if [ "$action" = "stop" ]; then
		SERVICE_ACTION="$action" $script
		rm -f  /tmp/icc.json
	fi
}

















